In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("NY_airbnb.csv")
df.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

# EDA

In [3]:
df.describe()


id       host_id      latitude     longitude         price  \
count  4.889500e+04  4.889500e+04  48895.000000  48895.000000  48895.000000   
mean   1.901714e+07  6.762001e+07     40.728949    -73.952170    152.720687   
std    1.098311e+07  7.861097e+07      0.054530      0.046157    240.154170   
min    2.539000e+03  2.438000e+03     40.499790    -74.244420      0.000000   
25%    9.471945e+06  7.822033e+06     40.690100    -73.983070     69.000000   
50%    1.967728e+07  3.079382e+07     40.723070    -73.955680    106.000000   
75%    2.915218e+07  1.074344e+08     40.763115    -73.936275    175.000000   
max    3.648724e+07  2.743213e+08     40.913060    -73.712990  10000.000000   

       minimum_nights  number_of_reviews  reviews_per_month  \
count    48895.000000       48895.000000       38843.000000   
mean         7.029962          23.274466           1.373221   
std         20.510550          44.550582           1.680442   
min          1.000000           0.000000           0.010000   
25%          1.000000           1.000000           0.190000   
50%          3.000000           5.000000           0.720000   
75%          5.000000          24.000000           2.020000   
max       1250.000000         629.000000          58.500000   

       calculated_host_listings_count  availability_365  
count                    48895.000000      48895.000000  
mean                         7.143982        112.781327  
std                         32.952519        131.622289  
min                          1.000000          0.000000  
25%                          1.000000          0.000000  
50%                          1.000000         45.000000  
75%                          2.000000        227.000000  
max                        327.000000        365.000000

In [4]:
df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [5]:
df['neighbourhood_group'].value_counts()

Manhattan        21661
Brooklyn         20104
Queens            5666
Bronx             1091
Staten Island      373
Name: neighbourhood_group, dtype: int64

In [6]:
df['neighbourhood'].value_counts()

Williamsburg          3920
Bedford-Stuyvesant    3714
Harlem                2658
Bushwick              2465
Upper West Side       1971
                      ... 
Fort Wadsworth           1
Richmondtown             1
New Dorp                 1
Rossville                1
Willowbrook              1
Name: neighbourhood, Length: 221, dtype: int64

In [7]:
df['room_type'].value_counts()

Entire home/apt    25409
Private room       22326
Shared room         1160
Name: room_type, dtype: int64

# Preparacion de datos y sus transformadores

In [8]:
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [9]:
df.drop(["id", "host_name", "name", "number_of_reviews", "last_review", "reviews_per_month", "neighbourhood", "calculated_host_listings_count", "host_id"], axis=1, inplace=True)

In [10]:
df.head()

neighbourhood_group  latitude  longitude        room_type  price  \
0            Brooklyn  40.64749  -73.97237     Private room    149   
1           Manhattan  40.75362  -73.98377  Entire home/apt    225   
2           Manhattan  40.80902  -73.94190     Private room    150   
3            Brooklyn  40.68514  -73.95976  Entire home/apt     89   
4           Manhattan  40.79851  -73.94399  Entire home/apt     80   

   minimum_nights  availability_365  
0               1               365  
1               1               355  
2               3               365  
3               1               194  
4              10                 0

In [11]:
df['room_type'].value_counts()

Entire home/apt    25409
Private room       22326
Shared room         1160
Name: room_type, dtype: int64

In [12]:
from sklearn.preprocessing import OneHotEncoder

Nominal_codificador=OneHotEncoder(sparse=False)
Nominal_codificador.fit_transform(df[['room_type']] )

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [13]:
Nominal_codificador.categories_

[array(['Entire home/apt', 'Private room', 'Shared room'], dtype=object)]

In [14]:
s2=df[df.price < 300] 

# Pipeline

###### esta funcion permite juntar varias transformaciones secuenciales que se requieren ejecutar a un conjunto de datos

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder  

In [16]:
categorical_list = ["neighbourhood_group","room_type"]
numeric_list = ["availability_365", "latitude", "longitude", "minimum_nights"]

In [17]:
numeric_transformer= Pipeline ( steps= [ ('scaler',StandardScaler() ) ] )
categorical_transformer= Pipeline ( steps= [ ('onehot',OneHotEncoder() ) ]  )                    

### Column Transformer

###### ej: permite aplicar una transformacion especifica o secuancia de transformaciones solo a las columnas numericas y una secuencia separada de transformaciones solo a las columnas categoricas 

###### Para aplicarlo, se debe especificar una lista de transformadores. 

###### Cada transformador es una TUPLA DE TRES ELEMENTOS que define el nombre del transformador, la transformacion a aplicar y los indicces de la ccolumna a los que aplicar. ej: **(Nombre, objeto, columnas)**

In [18]:
#Definir los transformadores, se utilizara cuando se aplicaran los algoritmos a machine learning

transformer = ColumnTransformer ( [
('cat',categorical_transformer,categorical_list) , ('num',numeric_transformer,numeric_list)
])

## Preparando las muestras de entrenamiento y prueba

In [19]:
X = s2.drop("price", axis=1)
y = s2["price"]

In [20]:
X.head()

neighbourhood_group  latitude  longitude        room_type  minimum_nights  \
0            Brooklyn  40.64749  -73.97237     Private room               1   
1           Manhattan  40.75362  -73.98377  Entire home/apt               1   
2           Manhattan  40.80902  -73.94190     Private room               3   
3            Brooklyn  40.68514  -73.95976  Entire home/apt               1   
4           Manhattan  40.79851  -73.94399  Entire home/apt              10   

   availability_365  
0               365  
1               355  
2               365  
3               194  
4                 0

In [21]:
y.head()

0    149
1    225
2    150
3     89
4     80
Name: price, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

# given:
# features: xs
# ground truth: ys

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.33,
                                                    random_state=0)

In [23]:
#aca me muestra la cantidad de datos a usar en training y test

X_train.shape,X_test.shape,y_train.shape,y_test.shape

((30134, 6), (14843, 6), (30134,), (14843,))

# Modelo lineal

In [24]:
from sklearn.linear_model import LinearRegression
linear_regression=LinearRegression()


In [25]:
#pipeline de la prediccion completa

model_linear_regression = Pipeline( [
    ('transformer',transformer),
    ('linear_regression', linear_regression)
    ] )



In [26]:
model_linear_regression .fit(X_train,y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['neighbourhood_group',
                                                   'room_type']),
                                                 ('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['availability_365',
                                                   'latitude', 'longitude',
                                                   'minimum_nights'])])),
                ('linear_regression', LinearRegression())])

In [27]:
#probamos con pocos datos
muestra_datos=X_test.iloc[4:]

model_linear_regression.predict(muestra_datos)

array([175.234375  ,  36.1640625 , 139.91796875, ..., 151.84375   ,
       145.16796875,  89.12890625])

In [28]:
#comparamos con los valores reales
list(y_test.iloc[:4])

[90, 110, 65, 40]

### Validacion cruzada

###### La validacion cruzada o cross validation (CV) es una de las tecnicas utilizadas para probar la efectividad de los modelos de Machine Learning, tambien es un procedimiento de remuestreo utilizado para evaluar un modelo si tenemos datos limitados.


###### Una manera de obtener las muestras es a traves del metodo del k-fold, el cual divide a los datos en k muestras 

##### **Evaluacion Linear Regresion**

In [29]:
# Evaluar el modelo usando crossvalidation

from sklearn.model_selection import cross_val_score

linear_scores=cross_val_score( model_linear_regression , X,y,
                             scoring='neg_mean_squared_error',cv=10)
linear_scores

array([-2248.51539458, -2003.26850071, -1912.01258523, -1860.77746677,
       -1900.3274423 , -1984.93674459, -1891.61429935, -2111.95858016,
       -2114.12592267, -2225.74441527])

In [30]:
# Cambiamos el signo negativo y sacamos la raiz

linear_rmse_scores = np.sqrt(-linear_scores)

linear_rmse_scores

array([47.41851321, 44.75788758, 43.72656613, 43.1367299 , 43.59274529,
       44.55262893, 43.49269248, 45.95605053, 45.97962508, 47.17779579])

In [31]:
# Definimos una funcion que nos devuelva el score, mean y sttandard deviation

def display_scores(scores):
    print('Scores:',scores)
    print('Mean:',scores.mean())
    print('Standard Deviation:',scores.std())

In [32]:
display_scores(linear_rmse_scores)

Scores: [47.41851321 44.75788758 43.72656613 43.1367299  43.59274529 44.55262893
 43.49269248 45.95605053 45.97962508 47.17779579]
Mean: 44.97912349195592
Standard Deviation: 1.4854578613281886


# Decision Tree

In [33]:
# Aplicara el modelo de arboles de decision con DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor

#1. Nombrar una variable para nuestro modelo
tree_reg=DecisionTreeRegressor(random_state=42)

#2. Definir el Pipeline: Transformacion + modelo
model_tree_reg = Pipeline(steps=[
    ('transformer',transformer) ,
    ('tree_reg',tree_reg)
])

#3. Ajustar el modelo
model_tree_reg.fit(X_train, y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['neighbourhood_group',
                                                   'room_type']),
                                                 ('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['availability_365',
                                                   'latitude', 'longitude',
                                                   'minimum_nights'])])),
                ('tree_reg', DecisionTreeRegressor(random_state=42))])

In [34]:
#Evaluacion
#4. Calcular el score con la validacion cruzada CV=10
tree_reg_scores = cross_val_score( model_tree_reg, X, y ,
                                  scoring='neg_mean_squared_error',cv=10)

#5. Realizar el cambio de signo  sacar la raiz
tree_rmse_scores=np.sqrt(-tree_reg_scores )

#6. Mostrar el resultado usando la funcion display_scores
display_scores(tree_rmse_scores)

Scores: [62.83317775 58.48746982 58.43265021 57.38319084 56.70246779 56.8794369
 57.91865779 58.10665127 56.28263637 61.68187553]
Mean: 58.47082142835372
Standard Deviation: 2.034967649731614


# RandomForest

In [35]:
# Aplicar el modelo RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor

In [36]:
#1. Nombrar una variable para nuestro modelo
forest_reg=RandomForestRegressor(n_estimators=10, random_state=42)

#2. Definir el Pipeline: Transformacion + modelo
model_forest_reg = Pipeline(steps=[
    ('transformer',transformer) ,
    ('forest_reg',forest_reg)
])

#3. Ajustar el modelo
model_forest_reg.fit(X_train, y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['neighbourhood_group',
                                                   'room_type']),
                                                 ('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['availability_365',
                                                   'latitude', 'longitude',
                                                   'minimum_nights'])])),
                ('forest_reg',
                 RandomForestRegressor(n_estimators=10, random_state=42))])

In [37]:
#Evaluacion
#4. Calcular el score con la validacion cruzada CV=10
forest_reg_scores = cross_val_score( model_forest_reg, X, y ,
                                  scoring='neg_mean_squared_error',cv=10)

#5. Realizar el cambio de signo  sacar la raiz
forest_rmse_scores=np.sqrt(-forest_reg_scores )

#6. Mostrar el resultado usando la funcion display_scores
display_scores(forest_rmse_scores)

Scores: [47.57977705 44.61933168 43.83415527 43.11249083 42.96639605 44.30542686
 43.69204812 45.08249435 44.58632713 46.95038103]
Mean: 44.672882837098214
Standard Deviation: 1.4478473042540794


# Resumen

<img src="resumen.PNG" style="width:400px;height:75px"/>

In [38]:
# Datos de evaluacion
list_model=['Linear_regression', 'DecisionTree', 'Random Forest']
list_mean=[45,58,45]
list_sd=[1,2,1]


In [39]:
# Agregamos una grafica para comparar visualmente los resultados

plt.figure(figsize=(4,5))
for i in range(3):
    plt.errobar(i, list_mean[i], xerr=0, yerr=list_sd[i],fmt='0',linewidth =3)
plt.xticks ( [0,1,2] , list_model)
plt.title("Evaluacion de los modelos")
plt.ylim(0,120000)
plt.grid(b=True, which='major', color='#666666', linestyle='-')
plt.minortricks_on()
plt.grid(b=True, which='minor', color='#666666', linestyle='-', alpha=0.2)
plt.show()    

AttributeError: module 'matplotlib.pyplot' has no attribute 'errobar'

<Figure size 400x500 with 0 Axes>